# Generated by Django 5.1 on 2024-08-31 12:34

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Image file attached to the message.', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, help_text='File attached to the message, can be any type of file.', null=True, upload_to='media/attachments/'),
        ),
    ]
