# Generated by Django 5.1 on 2024-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_attachment_image_alter_attachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='Name of the chat room. Optional for private chats, recommended for group chats.', max_length=255, null=True, unique=True),
        ),
    ]
