# Generated by Django 5.1 on 2024-09-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommembership',
            name='has_write_access',
            field=models.BooleanField(default=True, help_text='Indicates whether the user has write access in the chat room.'),
        ),
    ]
