# Generated by Django 5.1 on 2025-02-15 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroommembership_has_write_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommembership',
            name='oponent_user',
            field=models.ForeignKey(blank=True, help_text='User who is the oponent in the private chat.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oponent_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
