# Generated by Django 5.1 on 2024-09-06 18:36

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='members',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='User who created this chat room.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_of_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, help_text='File attached to the message, can be any type of file.', null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Image file attached to the message.', null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='ChatRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this model instance.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the instance was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the instance was last updated.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], default='ACTIVE', help_text='Status of the instance, typically used for soft deletion.', max_length=20)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CO_ADMIN', 'Co Admin'), ('MODERATOR', 'Moderator'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', help_text='Role of the user in the chat room.', max_length=20)),
                ('chat_room', models.ForeignKey(help_text='Chat room in which the user is a member.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.chatroom')),
                ('user', models.ForeignKey(help_text='User who is a member of the chat room.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ChatRoomInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this model instance.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the instance was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the instance was last updated.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], default='ACTIVE', help_text='Status of the instance, typically used for soft deletion.', max_length=20)),
                ('is_accepted', models.BooleanField(default=False, help_text='Indicates whether the invitation is accepted by the invitee.')),
                ('invitation_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the invitation.', max_length=20)),
                ('chat_room', models.ForeignKey(blank=True, help_text='Chat room for which the invitation is sent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.chatroom')),
                ('receiver', models.ForeignKey(help_text='User who is invited to the chat room.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_invitations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the invitation to the chat room.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('member_ship', models.ForeignKey(blank=True, help_text='Membership of the user in the chat room.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_invitations', to='chat.chatroommembership')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='chatroommembership',
            constraint=models.UniqueConstraint(fields=('user', 'chat_room'), name='unique_user_chat_room_membership'),
        ),
        migrations.AddConstraint(
            model_name='chatroominvitation',
            constraint=models.UniqueConstraint(fields=('chat_room', 'receiver'), name='unique_chat_room_invitation'),
        ),
    ]
