# Generated by Django 5.1 on 2025-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroommembership_oponent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the chat room. Optional for private chats, recommended for group chats.', max_length=255, unique=True),
        ),
    ]
