# Generated by Django 5.1 on 2024-09-06 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatroom_admin_remove_chatroom_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroominvitation',
            name='unique_chat_room_invitation',
        ),
        migrations.AddConstraint(
            model_name='chatroominvitation',
            constraint=models.UniqueConstraint(fields=('chat_room', 'receiver', 'sender'), name='unique_chat_room_invitation'),
        ),
    ]
