# Generated by Django 5.1 on 2024-09-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatroominvitation_unique_chat_room_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommembership',
            name='member_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('REMOVED', 'Removed'), ('BLOCKED_BY_ADMIN', 'Blocked by Admin'), ('BLOCKED_BY_SYSTEM', 'Blocked by System')], default='ACTIVE', help_text='Status of the member in the chat room.', max_length=20),
        ),
    ]
