# Generated by Django 5.1 on 2024-09-07 11:09

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroommembership_member_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroominvitation',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='chatroominvitation',
            name='member_ship',
        ),
        migrations.AlterField(
            model_name='chatroominvitation',
            name='chat_room',
            field=models.ForeignKey(default=1, help_text='Chat room for which the invitation is sent.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.chatroom'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this model instance.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the instance was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the instance was last updated.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], default='ACTIVE', help_text='Status of the instance, typically used for soft deletion.', max_length=20)),
                ('blocked_by', models.ForeignKey(help_text='User who blocked the user.', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('member_ship', models.ForeignKey(blank=True, help_text='User who is blocked in the chat room.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='chat.chatroommembership')),
                ('user', models.ForeignKey(blank=True, help_text='User who is blocked.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'blocked_by'), name='unique_blocked_user')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
